<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Suit_Registro_UAT</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>05eb3e27-b583-459e-82da-360a7bfac2ec</testSuiteGuid>
   <testCaseLink>
      <guid>81e2ab31-0f2d-417c-b52b-3372d17e69a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Servi2cliente/Registro_UAT/Llenar Campo Correo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20d8156b-3152-4a15-b9c4-1796578c5dcf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fabbed41-91ff-4bde-8e2d-056b09c21841</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e8db4fd-4751-4335-90a8-c7f229b180f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>544b9bd7-0616-4786-b9d4-3c95171cf1a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4452c7a-92c0-469f-bb99-d2a5e41bf7a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79ac3bd7-38c3-4a41-b86d-dd827a799be2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fc018cf-ac27-4cc6-a1bf-8d2abb899c69</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f9ed04d-fcbf-4292-bd03-a901548a566c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Servi2cliente/Registro_UAT/Llenar Campo Correo Confirmar</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>914c9826-c10a-427f-85fe-5295745d1089</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c15e0484-1bd2-4c8a-9288-5544d3a00b87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f8792f9-7522-438d-a7c9-4dd7ee10e7cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>066f9b89-3f66-4b50-b0e2-efdc86089463</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c18a0f7-d719-4241-9f1e-04859ce72158</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca577ceb-9c87-450d-bd9d-174dd847e353</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ce02d9e-bc7b-4cab-bdf6-06048cd6c3a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b7fc0d9-76de-4a66-a4e0-acea8946943d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24b2ec28-a815-40eb-a3d0-563dff0fc8e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Servi2cliente/Registro_UAT/Llenar Campo Interlocutor</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb10f5a1-e5c8-4185-9408-4ecad0984ff2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe4072fd-9683-4444-882d-12526b2029ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56f213f2-e569-4335-bace-d24148645c76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Servi2cliente/Registro_UAT/Llenar Campo NumberAccount</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb10f5a1-e5c8-4185-9408-4ecad0984ff2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe4072fd-9683-4444-882d-12526b2029ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a49c00f-0706-4ef3-b8ef-5e679d8425ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Servi2cliente/Registro_UAT/Llenar Campos Nombre y Apellido</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d822f1f-29ff-45ca-98ed-5ad3e677e24b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f0fdc63-e220-4291-9223-803e1a7b7d18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9062a5ba-2228-41f2-8cd9-fff6026e95aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13150452-9948-4e48-98d7-7f5128776676</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39f5be05-b653-41c1-b9bf-9de5e9498aff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Servi2cliente/Registro_UAT/Registro Check Engie</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>499a7392-8e72-4d58-be89-c237fcb26a80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Servi2cliente/Registro_UAT/Verificar Icono Interlocutor y NumberAccount</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>29fa76fb-b57d-4844-b5da-035c56316e11</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Servi2cliente/Registro_UAT/Verificar Icono Search</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b1e5b73c-89ca-423c-9fb8-c9e72affbe84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Servi2cliente/Registro_UAT/Verificar Icono Search II</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
