<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Registrarse_II</name>
   <tag></tag>
   <elementGuidId>411f3b92-2e3d-43f0-8c40-65f147682933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mat-tab-label-0-1&quot;]
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-tab-label-0-1
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
