<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_Registrar_Form_Factura_Clave_Cliente</name>
   <tag></tag>
   <elementGuidId>ea88b9cd-71f9-4a89-a2cb-3555d66b3899</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui-overlaypanel-content > img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'assets/images/factura_clave_cliente.jpg']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-overlaypanel/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/factura_clave_cliente.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;master-conteiner&quot;]/register-form[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;p-grid no-margin ng-star-inserted&quot;]/div[@class=&quot;wrapper p-grid no-padding p-justify-center&quot;]/div[@class=&quot;p-col-12 no-padding&quot;]/div[@class=&quot;p-col-12 no-padding&quot;]/form[@class=&quot;ng-invalid ng-star-inserted ng-dirty ng-touched&quot;]/div[@class=&quot;ng-star-inserted&quot;]/client-engie-form[1]/div[@class=&quot;registrarme ng-dirty ng-invalid ng-touched&quot;]/div[@class=&quot;ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/section[@class=&quot;p-grid p-col-12 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;p-col-12 p-sm-6 p-md-4&quot;]/p-overlaypanel[@class=&quot;ng-tns-c5-2&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c5-2 ui-overlaypanel ui-widget ui-widget-content ui-corner-all ui-shadow ng-star-inserted&quot;]/div[@class=&quot;ui-overlaypanel-content&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-overlaypanel/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
