<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alert_Home_Login_Email_Invalido_II</name>
   <tag></tag>
   <elementGuidId>71bf9d10-d6ab-4559-bb84-b9221fdff836</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui-toast-message-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/p-toast/div/p-toastitem/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-toast-message-content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ErrorEl email especificado no es válido</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/p-toast[@class=&quot;ng-tns-c3-0&quot;]/div[@class=&quot;ng-tns-c3-0 ui-toast ui-widget ui-toast-top-right&quot;]/p-toastitem[@class=&quot;ng-tns-c4-2 ng-trigger ng-trigger-toastAnimation ng-tns-c3-0 ng-star-inserted&quot;]/div[@class=&quot;ui-toast-message ui-shadow ui-toast-message-error ng-trigger ng-trigger-messageState&quot;]/div[@class=&quot;ui-toast-message-content&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='chat'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='phone'])[1]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-toastitem/div/div</value>
   </webElementXpaths>
</WebElementEntity>
