<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Restablecer_Contrasea</name>
   <tag></tag>
   <elementGuidId>b5aa8ab7-1a32-433b-832d-5623da1526cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mail']/div/div/table/tbody/tr/td/table/tbody/tr[4]/td/table/tbody/tr[2]/td/table/tbody/tr/td/div/table/tbody/tr/td/div[2]/font/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://mandrillapp.com/track/click/30535523/uatservi2.tutenlabs.dev?p=eyJzIjoiN2swMnBtbGdHRWpvQ0tad2l1blM2c3BpdTQwIiwidiI6MSwicCI6IntcInVcIjozMDUzNTUyMyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3VhdHNlcnZpMi50dXRlbmxhYnMuZGV2XFxcL2NsaWVudGVzXFxcL2NhbWJpYXItY29udHJhc2VuYT90b2tlbj1INUNSeXRoU0JlZUQyWkRIeDF0V21xVE9KbXBWa0xTbXFvRTVPNVVlWTlcIixcImlkXCI6XCJmMTVlN2RkYmFkNzc0NjcwOGNjZjI1MjA5MTYwZjhmNFwiLFwidXJsX2lkc1wiOltcIjQ5MWFhYmZkYmUxNjBjYjdkOTcyN2E4ZjM3NzIzOGRkZTczMzkwNGNcIl19In0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Restablecer contraseña</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail&quot;)/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[4]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[2]/font[1]/span[1]/a[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Var_registro_UTA/Page_YOPmail/iframe/iframe_Undo_ifmail</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mail']/div/div/table/tbody/tr/td/table/tbody/tr[4]/td/table/tbody/tr[2]/td/table/tbody/tr/td/div/table/tbody/tr/td/div[2]/font/span/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Restablecer contraseña')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hola victoriasosa37@yopmail.com,'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Restablecer contraseña']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://mandrillapp.com/track/click/30535523/uatservi2.tutenlabs.dev?p=eyJzIjoiN2swMnBtbGdHRWpvQ0tad2l1blM2c3BpdTQwIiwidiI6MSwicCI6IntcInVcIjozMDUzNTUyMyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3VhdHNlcnZpMi50dXRlbmxhYnMuZGV2XFxcL2NsaWVudGVzXFxcL2NhbWJpYXItY29udHJhc2VuYT90b2tlbj1INUNSeXRoU0JlZUQyWkRIeDF0V21xVE9KbXBWa0xTbXFvRTVPNVVlWTlcIixcImlkXCI6XCJmMTVlN2RkYmFkNzc0NjcwOGNjZjI1MjA5MTYwZjhmNFwiLFwidXJsX2lkc1wiOltcIjQ5MWFhYmZkYmUxNjBjYjdkOTcyN2E4ZjM3NzIzOGRkZTczMzkwNGNcIl19In0')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
   </webElementXpaths>
</WebElementEntity>
