<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alert_All_Values</name>
   <tag></tag>
   <elementGuidId>dcb79b04-24e6-437e-b4fd-c3ef0939344e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/div/register-form/div/div[2]/div[2]/div/form/div[2]/client-engie-form/div/div[2]/small</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
